name: DevCard

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@3.0.0
        with:
          # devcard_id: "53b897c2cd2d443ab289eebb8f39b3c8"
          devcard_id: "QlchbvX67"
